import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--use-gl=angle','--enable-unsafe-swiftshader','--no-proxy-server']});
const page=await browser.newPage({viewport:{width:640,height:400}});
page.on('pageerror',e=>console.error('PAGEERROR',e.message));
await page.goto('http://127.0.0.1:8137/',{waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>window.__aquarium?.ready===true&&document.body.dataset.labState==='ready',undefined,{timeout:60000});
await page.waitForTimeout(1500);
const probe=()=>page.evaluate(()=>window.__aquarium.stats());
await page.evaluate(()=>window.__aquarium.setScenario('hunt'));
console.log('t0:',JSON.stringify(await probe()));
await page.waitForTimeout(4000);
console.log('t4:',JSON.stringify(await probe()));
await page.waitForTimeout(4000);
console.log('t8:',JSON.stringify(await probe()));
const ctrl=await page.evaluate(()=>window.__aquarium.setControlValue('timeScale',300)&&document.querySelector('#timeScaleOut').textContent);
console.log('timeScale out:',ctrl);
await page.waitForTimeout(4000);
console.log('t12:',JSON.stringify(await probe()));
await browser.close();
